### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by bomzj** [ArnoNuyts/contentful2hugo#2]
Executing "c2h -v" gives an error containing "SSL_connect returned=1 errno=0 state=error: certificate verify failed"

**Comment by wmakley** [comment]
This is probably not c2h's fault; it is just a wrapper for the ruby Net::HTTP library. This is more likely a problem with using an old version of ruby, compiling it against an older openssl. Sometimes your system's CA certs can be out of date, but I haven't actually seen that except for unsupported OSes.

**Comment by wmakley** [comment]
I would also kind of plug my fork: https://github.com/tortus/contentful2hugo I made a bunch of basic QOL improvements I'd love to get merged in (including the ability to see what happens when it breaks), but it doesn't seem like much is happening here in general.

**Comment by bomzj** [comment]
Thanks for answers, I found the solution by adding needed certs.
